# Generated by Django 5.0.2 on 2024-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.CharField(max_length=1000, null=True, verbose_name='Logo'),
        ),
    ]
